import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('en'), Locale('mn')];

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'appName': 'RidePool',
      'appTagline': 'Share rides, save money',
      'home': 'Home',
      'trips': 'Trips',
      'wallet': 'Wallet',
      'profile': 'Profile',
      'language': 'Language',
      'english': 'English',
      'mongolian': 'Mongolian',
      'welcomeAboard': 'Welcome aboard or back',
      'enterNumberPrompt': 'To sign up or log in, enter your number.',
      'passengerTitle': "I'm a Passenger",
      'passengerSubtitle': 'Find rides & share trips',
      'driverTitle': "I'm a Driver",
      'driverSubtitle': 'Offer rides & earn money',
      'termsNotice':
          'By continuing, you agree to our Terms of Service and Privacy Policy',
      'welcomeToRideShare': 'Welcome to RideShare',
      'startEarningDriver': 'Start earning as a driver',
      'getRideMinutes': 'Get a ride in minutes',
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'enterEmailPassword': 'Please enter email and password',
      'enterName': 'Please enter your name',
      'authLoginTitle': 'Sign In',
      'authLoginSubtitle': 'Enter your credentials to continue',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'dontHaveAccount': "Don't have an account? Sign up",
      'alreadyHaveAccount': 'Already have an account? Sign in',
      'authSignupSubtitle': 'Tell us a bit about yourself',
      'accountCreated': 'Account Created!',
      'getStarted': 'Get Started',
      'hiDriver': 'Hi, {name} 👋',
      'online': '• Online',
      'offline': '• Offline',
      'routes': 'Routes',
      'done': 'Done',
      'myRoutes': 'My Routes',
      'earnings': 'Earnings',
      'createNewRoute': 'Create New Route',
      'youAreOnline': 'You are Online',
      'goOnline': 'Go Online',
      'acceptingRides': 'Accepting rides',
      'tapToStartEarning': 'Tap to start earning',
      'couldNotLoadDashboard': 'Could not load dashboard',
      'pleaseSignInAgain': 'Please sign in again',
      'noTripsYet': 'No trips yet',
      'noRideRequestsYet': 'No ride requests yet',
      'createRouteAndGoOnline':
          'Create a route and go online to start receiving trips.',
      'tripDataLoaded': 'Your trip data is loading from the backend now.',
      'tripHistory': 'Trip History',
      'all': 'All',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'noTripsFound': 'No trips found',
      'unknownPickup': 'Unknown pickup',
      'unknownDestination': 'Unknown destination',
      'passengerTrip': 'Passenger Trip',
      'driverTrip': 'Driver Trip',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'routeNotFound': 'Route not found',
      'createRoute': 'Create Route',
      'editRoute': 'Edit Route',
      'routeNameOptional': 'Route Name (Optional)',
      'routeNameHint': 'e.g., Daily Office Commute',
      'startPoint': 'Start Point',
      'startPointHint': 'Enter starting location',
      'addStop': 'Add Stop',
      'enterStopLocation': 'Enter stop location',
      'dropOffPoint': 'Drop-off Point',
      'dropOffHint': 'Enter destination',
      'roundTrip': 'Round Trip',
      'includeReturnJourney': 'Include return journey',
      'repeatOn': 'Repeat on',
      'capacityPricing': 'Capacity & Pricing',
      'seats': 'Seats',
      'availableSeats': 'Available Seats',
      'pricePerSeat': 'Price per Seat',
      'potentialEarnings': 'Potential Earnings',
      'potentialEarningsPerTrip': 'Potential earnings per trip',
      'saveRouteTemplate': 'Save Route Template',
      'saveChanges': 'Save Changes',
      'add': 'Add',
      'departure': 'Departure',
      'return': 'Return',
      'continueWithGoogle': 'Continue with Google',
      'forgotPassword': 'Forgot password?',
      'resetPassword': 'Reset Password',
      'newPassword': 'New Password',
      'reset': 'Reset',
      'passwordResetSuccess': 'Password reset successful. You can now sign in.',
      'phone': 'Phone',
      'gender': 'Gender',
      'age': 'Age',
      'carModel': 'Car model',
      'carPlate': 'Car plate',
      'driverId': 'Driver ID',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'requiredProfileFields': 'Phone, gender, and valid age are required',
      'requiredDriverFields':
          'Car model, plate, and driver ID are required for drivers',
      'tryAgain': 'Try Again',
      'cancel': 'Cancel',
      'refresh': 'Refresh',
      'findSharedRides': 'Find Shared Rides',
      'confirmRequest': 'Confirm & Request',
      'pleaseEnterDestination': 'Please enter destination',
      'pleaseLogInBeforeRide': 'Please log in before requesting a ride.',
      'browseSharedRoutes': 'Browse Shared Routes',
      'searchRoutes': 'Search routes',
      'requestThisRide': 'Request this ride',
      'driver': 'Driver',
      'unknownDriver': 'Unknown driver',
      'activeTrips': 'Active trips',
      'tripActivityOverview': 'Trip Activity Overview',
      'performance': 'Performance',
      'recentTrips': 'Recent Trips',
      'fromBackendTrips': 'From backend trips',
      'publish': 'Publish',
      'uploadRequiredDocuments': 'Upload required documents',
      'uploading': 'Uploading...',
      'tapToUpload': 'Tap to upload',
      'orDragAndDrop': 'or drag and drop',
      'takePhoto': 'Take Photo',
      'uploadFromGallery': 'Upload from Gallery',
      'typeMessage': 'Type a message...',
    },
    'mn': {
      'appName': 'RidePool',
      'appTagline': 'Унаа хуваалцаж, мөнгөө хэмнэе',
      'home': 'Нүүр',
      'trips': 'Аяллууд',
      'wallet': 'Хэтэвч',
      'profile': 'Профайл',
      'language': 'Хэл',
      'english': 'Англи',
      'mongolian': 'Монгол',
      'welcomeAboard': 'Тавтай морилно уу',
      'enterNumberPrompt':
          'Бүртгүүлэх эсвэл нэвтрэхийн тулд дугаараа оруулна уу.',
      'passengerTitle': 'Би зорчигч',
      'passengerSubtitle': 'Унаа хайж, аяллаа хуваалц',
      'driverTitle': 'Би жолооч',
      'driverSubtitle': 'Унаа санал болгож, орлого ол',
      'termsNotice':
          'Үргэлжлүүлснээр та Үйлчилгээний нөхцөл болон Нууцлалын бодлогыг зөвшөөрнө.',
      'welcomeToRideShare': 'RideShare-д тавтай морил',
      'startEarningDriver': 'Жолоочоор орлого олж эхэл',
      'getRideMinutes': 'Хэдхэн минутын дотор унаа захиалаарай',
      'signIn': 'Нэвтрэх',
      'createAccount': 'Бүртгэл үүсгэх',
      'enterEmailPassword': 'Имэйл болон нууц үгээ оруулна уу',
      'enterName': 'Нэрээ оруулна уу',
      'authLoginTitle': 'Нэвтрэх',
      'authLoginSubtitle': 'Үргэлжлүүлэхийн тулд мэдээллээ оруулна уу',
      'email': 'Имэйл',
      'password': 'Нууц үг',
      'fullName': 'Овог нэр',
      'dontHaveAccount': 'Бүртгэлгүй юу? Бүртгүүлнэ үү',
      'alreadyHaveAccount': 'Бүртгэлтэй юу? Нэвтэрнэ үү',
      'authSignupSubtitle': 'Өөрийнхөө талаар бага зэрэг мэдээлэл өгнө үү',
      'accountCreated': 'Бүртгэл үүслээ!',
      'getStarted': 'Эхлэх',
      'hiDriver': 'Сайн байна уу, {name} 👋',
      'online': '• Онлайн',
      'offline': '• Офлайн',
      'routes': 'Чиглэлүүд',
      'done': 'Дууссан',
      'myRoutes': 'Миний чиглэлүүд',
      'earnings': 'Орлого',
      'createNewRoute': 'Шинэ чиглэл үүсгэх',
      'youAreOnline': 'Та онлайн байна',
      'goOnline': 'Онлайн болох',
      'acceptingRides': 'Захиалга авч байна',
      'tapToStartEarning': 'Орлого олохын тулд дарна уу',
      'couldNotLoadDashboard': 'Самбарын мэдээллийг ачаалж чадсангүй',
      'pleaseSignInAgain': 'Дахин нэвтэрнэ үү',
      'noTripsYet': 'Одоогоор аялал алга',
      'noRideRequestsYet': 'Одоогоор хүсэлт алга',
      'createRouteAndGoOnline':
          'Чиглэл үүсгээд онлайн болж аялал хүлээн аваарай.',
      'tripDataLoaded':
          'Таны аяллын мэдээлэл одоо backend-ээс ачаалагдаж байна.',
      'tripHistory': 'Аяллын түүх',
      'all': 'Бүгд',
      'completed': 'Дууссан',
      'cancelled': 'Цуцлагдсан',
      'noTripsFound': 'Аялал олдсонгүй',
      'unknownPickup': 'Суух цэг тодорхойгүй',
      'unknownDestination': 'Очих цэг тодорхойгүй',
      'passengerTrip': 'Зорчигчийн аялал',
      'driverTrip': 'Жолоочийн аялал',
      'today': 'Өнөөдөр',
      'yesterday': 'Өчигдөр',
      'routeNotFound': 'Хуудас олдсонгүй',
      'createRoute': 'Чиглэл үүсгэх',
      'editRoute': 'Чиглэл засах',
      'routeNameOptional': 'Чиглэлийн нэр (заавал биш)',
      'routeNameHint': 'ж: Өдөр бүрийн оффисын чиглэл',
      'startPoint': 'Эхлэх цэг',
      'startPointHint': 'Эхлэх байршлыг оруулна уу',
      'addStop': 'Зогсоол нэмэх',
      'enterStopLocation': 'Зогсоолын байршлыг оруулна уу',
      'dropOffPoint': 'Буух цэг',
      'dropOffHint': 'Очих байршлыг оруулна уу',
      'roundTrip': 'Буцах чиглэлтэй',
      'includeReturnJourney': 'Буцах аяллыг оруулах',
      'repeatOn': 'Давтах өдрүүд',
      'capacityPricing': 'Багтаамж ба үнэ',
      'seats': 'Суудал',
      'availableSeats': 'Боломжтой суудал',
      'pricePerSeat': 'Суудлын үнэ',
      'potentialEarnings': 'Боломжит орлого',
      'potentialEarningsPerTrip': 'Нэг аяллын боломжит орлого',
      'saveRouteTemplate': 'Чиглэлийн загвар хадгалах',
      'saveChanges': 'Өөрчлөлт хадгалах',
      'add': 'Нэмэх',
      'departure': 'Хөдлөх',
      'return': 'Буцах',
      'continueWithGoogle': 'Google-ээр үргэлжлүүлэх',
      'forgotPassword': 'Нууц үг мартсан уу?',
      'resetPassword': 'Нууц үг сэргээх',
      'newPassword': 'Шинэ нууц үг',
      'reset': 'Сэргээх',
      'passwordResetSuccess':
          'Нууц үг амжилттай шинэчлэгдлээ. Одоо нэвтэрнэ үү.',
      'phone': 'Утас',
      'gender': 'Хүйс',
      'age': 'Нас',
      'carModel': 'Машины загвар',
      'carPlate': 'Машины дугаар',
      'driverId': 'Жолоочийн ID',
      'male': 'Эрэгтэй',
      'female': 'Эмэгтэй',
      'other': 'Бусад',
      'requiredProfileFields': 'Утас, хүйс, зөв нас шаардлагатай',
      'requiredDriverFields':
          'Жолоочийн хувьд машины загвар, дугаар, жолоочийн ID шаардлагатай',
      'tryAgain': 'Дахин оролдох',
      'cancel': 'Цуцлах',
      'refresh': 'Шинэчлэх',
      'findSharedRides': 'Хамт явах унаа хайх',
      'confirmRequest': 'Баталгаажуулж хүсэлт илгээх',
      'pleaseEnterDestination': 'Очих газраа оруулна уу',
      'pleaseLogInBeforeRide': 'Унаа хүсэхийн өмнө нэвтэрнэ үү.',
      'browseSharedRoutes': 'Хамтын чиглэлүүд үзэх',
      'searchRoutes': 'Чиглэл хайх',
      'requestThisRide': 'Энэ унааг хүсэх',
      'driver': 'Жолооч',
      'unknownDriver': 'Тодорхойгүй жолооч',
      'activeTrips': 'Идэвхтэй аяллууд',
      'tripActivityOverview': 'Аяллын үйл ажиллагааны тойм',
      'performance': 'Гүйцэтгэл',
      'recentTrips': 'Сүүлийн аяллууд',
      'fromBackendTrips': 'Backend аяллуудаас',
      'publish': 'Нийтлэх',
      'uploadRequiredDocuments': 'Шаардлагатай бичиг баримт оруулах',
      'uploading': 'Оруулж байна...',
      'tapToUpload': 'Оруулахын тулд дарна уу',
      'orDragAndDrop': 'эсвэл чирж оруулна уу',
      'takePhoto': 'Зураг авах',
      'uploadFromGallery': 'Галерейгаас оруулах',
      'typeMessage': 'Мессеж бичнэ үү...',
    },
  };

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  String get languageCode => locale.languageCode;

  String text(String key) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }

  String hiDriver(String name) => text('hiDriver').replaceAll('{name}', name);
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'mn'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture(AppLocalizations(locale));
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
